openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: Get all tasks
      tags:
        - tasks
      responses:
        '200':
          description: A list of all tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '404':
          description: No tasks found
    post:
      summary: Create a new task
      tags:
        - tasks
      requestBody:
        description: The task to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTask'
      responses:
        '201':
          description: The created task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
  /tasks/{task_id}:
    get:
      summary: Get a task by ID
      tags:
        - tasks
      parameters:
        - name: task_id
          in: path
          required: true
          description: The ID of the task to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: The task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
    patch:
      summary: Update a task by ID
      tags:
        - tasks
      parameters:
        - name: task_id
          in: path
          required: true
          description: The ID of the task to update
          schema:
            type: integer
      requestBody:
        description: The task with updated details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTask'
      responses:
        '200':
          description: The updated task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found or invalid update request
    delete:
      summary: Delete a task by ID
      tags:
        - tasks
      parameters:
        - name: task_id
          in: path
          required: true
          description: The ID of the task to delete
          schema:
            type: integer
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found or invalid request
  /tasks/user/{user_id}:
    get:
      summary: Get tasks for a specific user
      tags:
        - tasks
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user for whom tasks are being retrieved
          schema:
            type: integer
      responses:
        '200':
          description: A list of tasks for the specified user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '404':
          description: User not found or no tasks for this user
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the task
        task:
          type: string
          description: The description or title of the task
        is_done:
          type: boolean
          description: Task completion status
        user_id:
          type: integer
          description: The ID of the user who created the task
    CreateTask:
      type: object
      properties:
        task:
          type: string
          description: The description or title of the task
        is_done:
          type: boolean
          description: Whether the task is marked as done
        user_id:
          type: integer
          description: The ID of the user who is creating the task
      required:
        - task
        - user_id
    UpdateTask:
      type: object
      properties:
        task:
          type: string
          description: The updated description or title of the task
        is_done:
          type: boolean
          description: The updated task completion status
      required:
        - task
        - is_done




















